force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Pending_Amount__c.field-meta.xml
<CustomField>
    <fullName>Pending_Amount__c</fullName>
    <formula>Total_Amount__c  - Total_received_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pending Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Interest_Amount_Line_Item__c/Interest_Amount_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Interest Amount Line Item</label>
    <nameField>
        <displayFormat>INT-{0000}</displayFormat>
        <label>Interest Amount Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interest Amount Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_schedule__c/Payment_schedule__c.object-meta.xml
<CustomObject>
    <label>Payment schedule</label>
    <nameField>
        <label>Payment schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment schedules</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_schedule__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Payment schedules</relationshipLabel>
    <relationshipName>Payment_schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Interest_Amount__c.field-meta.xml
<CustomField>
    <fullName>Interest_Amount__c</fullName>
    <formula>If( Include_Interest__c ,if(Payment_Due_Date__c &lt; TODAY() &amp;&amp; ISBLANK(Last_Payment_Date__c),
(AmountB__c * Interest_Percent__c * (TODAY() - Payment_Due_Date__c))/365 ,
if(Last_Payment_Date__c &lt; TODAY() &amp;&amp; !ISBLANK(Last_Payment_Date__c),
(AmountB__c * Interest_Percent__c * (TODAY() - Last_Payment_Date__c))/365, 0.0)),0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interest Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Interest_Percent__c.field-meta.xml
<CustomField>
    <fullName>Interest_Percent__c</fullName>
    <label>Interest Percent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/PaymentDueDate__c.field-meta.xml
<CustomField>
    <fullName>PaymentDueDate__c</fullName>
    <formula>/*Master_Payment_Schedule__r.Completed_Date__c*/  Demanded_Date__c + (15 + Due_Date_Extension__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Pending_Amount__c.field-meta.xml
<CustomField>
    <fullName>Pending_Amount__c</fullName>
    <formula>if(Received_Amount1__c &gt; Amount__c ,0 , Amount__c  - Received_Amount1__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pending Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Received_Amount__c.field-meta.xml
<CustomField>
    <fullName>Received_Amount__c</fullName>
    <label>Received Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>Rc-{0000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt_Line_Item__c/Receipt_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Receipt Line Item</label>
    <nameField>
        <label>Receipt Line Item	 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Receipt Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt_Line_Item__c/fields/Payment_schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_schedule__c</fullName>
    <label>Payment schedule</label>
    <referenceTo>Payment_schedule__c</referenceTo>
    <relationshipLabel>Receipt Line Items</relationshipLabel>
    <relationshipName>Receipt_Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Receipt_Line_Item__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flat Amount</fullName>
            </value>
            <value>
                <fullName>GST Amount</fullName>
            </value>
            <value>
                <fullName>TDS</fullName>
            </value>
            <value>
                <fullName>Additional Charges</fullName>
            </value>
            <value>
                <fullName>Villa Amount</fullName>
            </value>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>Plot Amount</fullName>
            </value>
            <value>
                <fullName>Row House Amount</fullName>
            </value>
            <value>
                <fullName>Booking Amount</fullName>
            </value>
            <value>
                <fullName>TDS from Bank</fullName>
            </value>
            <value>
                <fullName>TDS Refund</fullName>
            </value>
            <value>
                <fullName>TDS Paid</fullName>
                <label>TDS Challan Entry</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReceiptLineIemTriggerHandler.cls
/****************************************************************
* Class Name   : ReceiptLineIemTriggerHandler
* Company      : Fingertipplus
* Created Date : 06-02-2026
* @description : This handler class contains all business logic
*                executed from Receipt_Line_Item__c trigger such as:
*                - Interest calculation on payment schedule
*                - Creation of Interest Amount Line Items
*                - Updating last payment date and time on schedule
*
* @author      : Durga Prasad
*
* Change Log:
* ----------------------------------------------------------------
* Ver | Author        | Date        | Description
* ----------------------------------------------------------------
* 1.0 | Durga Prasad | 04-02-2026  | Initial version
* ----------------------------------------------------------------
*****************************************************************/
public class ReceiptLineIemTriggerHandler {

    /**
     * Method Name  : afterInsert
     * Description  : Executes business logic after Receipt_Line_Item__c insert.
     *
     * Functionality:
     * 1. Collects inserted receipt line item Ids
     * 2. Calls approvedReceiptsHandler for further processing
     *
     * Used From:
     * - Receipt_Line_Item__c Trigger (after insert)
     */
    public static void afterInsert(List<Receipt_Line_Item__c> newReceiptlineItemList) {

        Set<Id> newReceiptlineItemIds = new Set<Id>();

        for (Receipt_Line_Item__c rcp : newReceiptlineItemList) {
            newReceiptlineItemIds.add(rcp.Id);
        }

        if (!newReceiptlineItemIds.isEmpty()) {
            approvedReceiptsHandler(newReceiptlineItemIds);
        }
    }


      /**
     * Method Name  : approvedReceiptsHandler
     * Description  : Handles payment schedule update and
     *                interest calculation after receipt approval.
     *
     * Functionality:
     * 1. Fetches Receipt_Line_Item__c linked to provided receipts.
     * 2. Retrieves related Payment_schedule__c records.
     * 3. For Payment schedules with Include_Interest__c = true:
     *      - Creates Interest_Amount_Line_Item__c record
     *      - Sets interest start date from last payment date
     *        or payment due date.
     *      - Sets interest end date as today.
     * 4. Updates on Payment Schedule:
     *      - Last_Payment_Date__c
     *      - Last_Payment_Time__c
     * 5. Inserts interest line items and updates schedules in bulk.
     *
     * Parameters:
     * @param receiptIds - Set of Receipt__c record Ids
     *
     * Used From:
     * - afterInsert method of ReceiptTriggerHandler
    */ 
    public static void approvedReceiptsHandler(Set<Id> newReceiptlineItemIds) {
        
        List<Receipt_Line_Item__c> recLinIds = [
            SELECT id, Name, Receipt__r.Receipt_date__c, Booking__c,
            Payment_schedule__c, Received_Amount__c,
            Payment_schedule__r.PaymentDueDate__c,
            Payment_schedule__r.Last_Payment_Date__c,
            Payment_schedule__r.Interest_Percent__c,
            Payment_Type__c,
            Payment_schedule__r.Include_Interest__c
            FROM Receipt_Line_Item__c 
            WHERE Id IN :newReceiptlineItemIds 
            AND Payment_Type__c != 'Interest'
        ];
        
        // One Schedule - Many Receipt Lines
        Map<Id, List<Receipt_Line_Item__c>> scheduleToReceipts = new Map<Id, List<Receipt_Line_Item__c>>();
        
        for (Receipt_Line_Item__c rli : recLinIds) {
            if (!scheduleToReceipts.containsKey(rli.Payment_schedule__c)) {
                scheduleToReceipts.put(rli.Payment_schedule__c, new List<Receipt_Line_Item__c>());
            }
            scheduleToReceipts.get(rli.Payment_schedule__c).add(rli);
        }
        
        List<Payment_schedule__c> payList1 = [
            SELECT id, name, Booking__c, PaymentDueDate__c,
            Last_Payment_Date__c, Include_Interest__c,
            Interest_Percent__c, Interest_Amount__c,
            Pending_Amount__c
            FROM Payment_schedule__c
            WHERE id IN :scheduleToReceipts.keySet()
        ];
        
        List<Interest_Amount_Line_Item__c> IntAmtLiEs = new List<Interest_Amount_Line_Item__c>();
        
        Date todayDate = Date.today();
        
        //  Process each schedule and its MULTIPLE receipts
        for (Payment_schedule__c pay : payList1) {
            
            List<Receipt_Line_Item__c> relatedReceipts = scheduleToReceipts.get(pay.Id);
            
            Date latestReceiptDate = pay.Last_Payment_Date__c;
            
            for (Receipt_Line_Item__c recipetItem : relatedReceipts) {
                
                // Track latest receipt date
                if (latestReceiptDate == null ||
                    recipetItem.Receipt__r.Receipt_date__c > latestReceiptDate) {
                        latestReceiptDate = recipetItem.Receipt__r.Receipt_date__c;
                    }
                
                //  Interest condition check
                if (
                    recipetItem.Payment_schedule__r.Include_Interest__c == true &&
                    recipetItem.Payment_schedule__r.PaymentDueDate__c != null &&
                    recipetItem.Received_Amount__c != null &&
                    recipetItem.Payment_schedule__r.Interest_Percent__c != null &&
                    recipetItem.Receipt__r.Receipt_date__c >
                    recipetItem.Payment_schedule__r.PaymentDueDate__c
                ) {
                    
                    Interest_Amount_Line_Item__c IntLine =
                        new Interest_Amount_Line_Item__c();
                    
                    Decimal days =
                        recipetItem.Payment_schedule__r.PaymentDueDate__c
                        .daysBetween(recipetItem.Receipt__r.Receipt_date__c);
                    
                    IntLine.Interest_Amount__c =(recipetItem.Received_Amount__c*recipetItem.Payment_schedule__r.Interest_Percent__c*days)/36500;
                    
                    // Start Date Logic
                    if (recipetItem.Payment_schedule__r.Last_Payment_Date__c == null) {
                        IntLine.Interest_Start_Date__c = recipetItem.Payment_schedule__r.PaymentDueDate__c;
                    } else {
                        IntLine.Interest_Start_Date__c = recipetItem.Payment_schedule__r.Last_Payment_Date__c;
                    }
                    
                    IntLine.Interest_End_Date__c = todayDate;
                    IntLine.Interest_Percent__c = recipetItem.Payment_schedule__r.Interest_Percent__c;
                    
                    IntLine.Payment_Schedule__c = recipetItem.Payment_Schedule__c;
                    
                    IntLine.Booking__c = recipetItem.Booking__c;
                    IntLine.Principal_Amount__c = recipetItem.Received_Amount__c;
                    
                    IntAmtLiEs.add(IntLine);
                }
            }
            
            // Update with latest receipt date
            pay.Last_Payment_Date__c = latestReceiptDate;
            pay.Last_Payment_Time__c = System.now();
        }
        
        if (!IntAmtLiEs.isEmpty()) {
            insert IntAmtLiEs;
        }
        
        update payList1;
    }
}