force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Agreement_Status__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Status__c</fullName>
    <defaultValue>&apos;Not Scheduled&apos;</defaultValue>
    <label>Agreement Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Scheduled</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Executed &amp; Registered</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Executed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Cancellation_Status__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Status__c</fullName>
    <label>Cancellation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <label>Pending From CRM Head</label>
            </value>
            <value>
                <fullName>Approved by CRM Head, Pending from Sales Head</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Booked</fullName>
                <default>true</default>
                <label>Booked</label>
            </value>
            <value>
                <fullName>Agreement</fullName>
            </value>
            <value>
                <fullName>Demands &amp; Progressive Collections</fullName>
            </value>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>Possession / Handover</fullName>
            </value>
            <value>
                <fullName>Customer Service &amp; Complaints</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Handed Over</fullName>
                <isActive>false</isActive>
                <label>Handed Over</label>
            </value>
            <value>
                <fullName>Maintenance</fullName>
                <isActive>false</isActive>
                <label>Maintenance</label>
            </value>
            <value>
                <fullName>Progressive Collections</fullName>
                <isActive>false</isActive>
                <label>Progressive Collections</label>
            </value>
            <value>
                <fullName>Swapping</fullName>
                <isActive>false</isActive>
                <label>Swapping</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <formula>Grand_Total_Before_GST__c +GST_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BookingCancellationApprovalController.cls
public class BookingCancellationApprovalController {
    public class DataBox {
        @auraEnabled public decimal cancellationAmount;
        @auraEnabled public boolean isAfterPostAggrement;
    }
   
    @AuraEnabled
    public static DataBox getRecordData(Id recordId) {
        DataBox db = new DataBox();
        // 1. Get Booking Data
        Booking__c bk =  [SELECT Id,Stage__c,Agreement_Status__c,Total_Amount__c FROM Booking__c WHERE Id = :recordId LIMIT 1];
        boolean isAfterPostAggrement = false;
        if(bk.Stage__c == 'Booked' || (bk.Stage__c =='Agreement' && (bk.Agreement_Status__c != 'Executed' && bk.Agreement_Status__c != 'Executed & Registered')))
        {
            db.cancellationAmount = 25000;
        }
        else
        {
            decimal amount = (bk.Total_Amount__c * 10)/100;
            db.cancellationAmount = amount;
            isAfterPostAggrement = true;
        }
        db.isAfterPostAggrement = isAfterPostAggrement;
        return db;
    }
    
    @AuraEnabled
    public static boolean sendCancellationApproval(Id recId, string cancellationReason, String cancellationRemarks, Decimal cancellationCharges,boolean isAfterPostAggrement){
        List<Booking__c> bklist = [Select Id, Name, Cancellation_Charge__c,Cancellation_Reason__c,	Stage__c,
                                   Cancellation_Description__c From Booking__c Where id =: recId];
        // Get Cancellation Amount from Custom Label
        Decimal cancellationAmount = 0;
        
        if(String.isNotBlank(Label.Cancellation_Amount)){
            cancellationAmount = Decimal.valueOf(
                Label.Cancellation_Amount.replace(',', '')
            );
        }
        
        for(Booking__c bk : bklist)
        {
            bk.Cancellation_Reason__c = cancellationReason;
            bk.Cancellation_Description__c = cancellationRemarks;
            bk.Cancellation_Charge__c = cancellationCharges;
            bk.Is_Cancelled__c = true;
            if((cancellationCharges >= cancellationAmount) && !isAfterPostAggrement) {
                bk.Cancellation_Status__c = 'Approved';
                bk.Stage__c = 'Cancellation';
            }
        }
        Update bklist;
        

        // Send for approval if cancellationCharges is less than defined Cancellation Amount
        if((cancellationCharges < cancellationAmount) || isAfterPostAggrement) {
            Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
            req1.setComments('Cancellation request');
            req1.setObjectId(recId);
            req1.setSubmitterId(userInfo.getUserId());
            req1.setProcessDefinitionNameOrId('Cancellation_Approval_For_Booking_heads');
            req1.setSkipEntryCriteria(true);
            Approval.ProcessResult result = Approval.process(req1);
        }
        return true;
    }
    
}