force-app/main/default/objects/Demand_Raised__c/Demand_Raised__c.object-meta.xml
<CustomObject>
    <label>Demand Raised</label>
    <nameField>
        <displayFormat>DR-{0000}</displayFormat>
        <label>Demand Raised Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demand Raised</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_schedule__c/Payment_schedule__c.object-meta.xml
<CustomObject>
    <label>Payment schedule</label>
    <nameField>
        <label>Payment schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment schedules</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_schedule__c/fields/Demanded_Date__c.field-meta.xml
<CustomField>
    <fullName>Demanded_Date__c</fullName>
    <label>Demanded Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_schedule__c/fields/Is_Demanded__c.field-meta.xml
<CustomField>
    <fullName>Is_Demanded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Demanded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CancelDemandNoteController.cls
public class CancelDemandNoteController {
    @AuraEnabled
    public static void cancelDemandNote(Id recId,String reason) {
        Demand_Raised__c demand = [SELECT Id,Name,Cancellation_Reason__c,Is_Cancelled__c,Demand_Status__c,Payment_schedule__c
                                   FROM Demand_Raised__c WHERE Id = :recId LIMIT 1];
        demand.Is_Cancelled__c = true;
        demand.Cancellation_Reason__c = reason;
        demand.Demand_Status__c = 'Demand Cancelled';
        update demand;
        
        Payment_Schedule__c paymentSchdule = [select Id,Name from Payment_Schedule__c where Id =:demand.Payment_schedule__c limit 1];
        paymentSchdule.Demanded_Date__c = null;
        paymentSchdule.Due_Date_Extension__c = 0;
        paymentSchdule.Is_Demanded__c = false;
        update paymentSchdule;
        
    }
}